default: &default
  adapter: postgresql
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: r_api_development

test:
  <<: *default
  database: r_api_test

production:
  <<: *default
  database: r_api_production
